# Generated by Django 4.2.4 on 2024-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcut',
            name='category',
            field=models.CharField(choices=[('F', 'Fashion'), ('DE', 'Daily Essentials'), ('Home', 'Homedecor'), ('El', 'Electronics'), ('Books', 'Books'), ('Outdoor', 'Outdoor')], max_length=10),
        ),
    ]
