# Generated by Django 4.2.4 on 2024-02-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker', '0007_ngo_requirment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='requirment',
            field=models.CharField(max_length=100),
        ),
    ]
