# Generated by Django 4.2.4 on 2024-03-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker', '0008_alter_ngo_requirment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcut',
            new_name='Product',
        ),
    ]
