# Generated by Django 4.2.4 on 2024-03-23 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sneaker', '0011_rename_requirment_ngo_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='password',
            field=models.CharField(default='Saumya@09', max_length=128),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
